In [1]:
import numpy as np

In [5]:
a = np.array([[1,2,3],[4,5,6]])

In [1]:
a

NameError: name 'a' is not defined

In [7]:
a.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6]])

In [8]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
np.reshape(a, 3)

ValueError: total size of new array must be unchanged

In [13]:
a.reshape(3,-1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a = a.reshape(3,-1)

In [16]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
type(a)

numpy.ndarray

In [18]:
type(a.reshape(3,-1))

numpy.ndarray

In [6]:
a = np.ones((5,1))

In [7]:
a

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.]])

In [3]:
a

array([ 1.,  1.,  1.,  1.,  1.])

In [1]:
a = random.rand(0,1
               )

NameError: name 'random' is not defined

In [2]:
import numpy as np

In [3]:
a = np.random.rand(0,1)

In [4]:
a

array([], shape=(0, 1), dtype=float64)

In [5]:
import random

In [6]:
a = random.random(0,1)

TypeError: random() takes no arguments (2 given)

In [11]:
a=  random.uniform(0,1)

In [12]:
a

0.3327917908346604

In [16]:
a =  np.array([[2,2,3],[1,4,4]])

In [25]:
avg = np.mean(a, axis = 0)

In [18]:
np.std(a, axis = 0)

array([ 0.5,  1. ,  0.5])

In [26]:
c=np.std(a, axis = 0)**2


In [28]:
a = (a - avg) / np.sqrt(c)

In [29]:
a

array([[ 1., -1., -1.],
       [-1.,  1.,  1.]])

In [2]:
np.pi

3.141592653589793

In [1]:
import numpy as np

In [2]:
a = np.array.shape((2,2))

AttributeError: 'builtin_function_or_method' object has no attribute 'shape'

In [3]:
a = np.array([2,2])

In [4]:
a

array([2, 2])

In [5]:
a = np.array((2,2))

In [6]:
a

array([2, 2])

In [7]:
np.array?

In [9]:
a.shape

(2,)

In [10]:
a.shape=[1,2]

In [11]:
a

array([[2, 2]])

In [12]:
a.shape=[2,1]

In [13]:
a

array([[2],
       [2]])

In [14]:
a.shape=[3,3]

ValueError: total size of new array must be unchanged

In [1]:
import numpy as np

In [2]:
a = np.array([0,128])

In [3]:
a

array([  0, 128])

In [2]:
import numpy as np
a = np.array([[1,2],[3,4]])

In [3]:
b = np.argmax(a)

In [4]:
b

3

In [5]:
a.shape

(2, 2)

In [6]:
b = np.amax(a)

In [7]:
b

4

In [ ]:
import numpy as np
D=np.random.randn(1000,500)
hidden_layer_sizes=[500]*10
nonlinearities=['tanh']*len(hidden_layer_sizes)

act = {'relu':lambda x:np.maximum(0,x), 'tanh':lambda x:np.tanh(x)}

Hs={}
for i in xrange(len(hidden_layer_sizes)):
    X=D if i==0 else Hs[i-1]
    fan_in = X.shape[1]
    fan_out = hidden_layer_sizes[i]
    W=np.random.randn(fan_in,fan_out)*0.01

    H=np.dot(X,W)
    H=act[nonlinearities[i]](H)
    Hs[i]=H

print 'input layer ahd mean %f and std %f' %(np.mean(D), np.std(D))
layer_means= [np.mean(H) for i, H in Hs.iteritems()]
layer_stds = [np.std(H) for i,H in Hs.iteritems()]

for i,H in Hs.iteritems():
    print 'hidden layer %d had mean %f and std %f' %(i+1, np.mean(H), np.std(H))

import matplotlib.pyplot as plt
%matplotlib inline
plt.figure()
plt.subplot(121)
plt.plot(Hs.keys(), layer_means, 'ob-')
plt.title('layer mean')
plt.subplot(122)
plt.plot(Hs.keys(), layer_stds, 'or-')
plt.title('layer std')

plt.figure()
for i,H in Hs.iteritems():
    plt.subplot(1, len(Hs), i+1)
    plt.hist(H.ravel(),30,range=(-1,1))
    
x = np.linspace(0, 2 * np.pi, 50)
plt.plot(x, np.sin(x)) # 如果没有第一个参数 x，图形的 x 坐标默认为数组的索引
plt.show() # 显示图形

In [ ]:
a=np.array(1,2)

In [ ]:
a.dim

In [1]:
a=1
print a

1


In [2]:
import numpy as np

In [4]:
a=np.array([1,2])

In [6]:
a.shape

(2,)

In [7]:
a=np.matrix(a)

In [8]:
a.dim

AttributeError: 'matrix' object has no attribute 'dim'

In [ ]:
import numpy as np
D=np.random.randn(1000,500)
hidden_layer_sizes=[500]*10
nonlinearities=['tanh']*len(hidden_layer_sizes)

act = {'relu':lambda x:np.maximum(0,x), 'tanh':lambda x:np.tanh(x)}

Hs={}
for i in xrange(len(hidden_layer_sizes)):
    X=D if i==0 else Hs[i-1]
    fan_in = X.shape[1]
    fan_out = hidden_layer_sizes[i]
    W=np.random.randn(fan_in,fan_out)*0.01

    H=np.dot(X,W)
    H=act[nonlinearities[i]](H)
    Hs[i]=H

print 'input layer ahd mean %f and std %f' %(np.mean(D), np.std(D))
layer_means= [np.mean(H) for i, H in Hs.iteritems()]
layer_stds = [np.std(H) for i,H in Hs.iteritems()]

for i,H in Hs.iteritems():
    print 'hidden layer %d had mean %f and std %f' %(i+1, np.mean(H), np.std(H))

import matplotlib.pyplot as plt
%matplotlib inline
plt.figure()
plt.subplot(121)
plt.plot(Hs.keys(), layer_means, 'ob-')
plt.title('layer mean')
plt.subplot(122)
plt.plot(Hs.keys(), layer_stds, 'or-')
plt.title('layer std')

plt.figure()
for i,H in Hs.iteritems():
    plt.subplot(1, len(Hs), i+1)
    plt.hist(H.ravel(),30,range=(-1,1))
    
x = np.linspace(0, 2 * np.pi, 50)
plt.plot(x, np.sin(x)) # 如果没有第一个参数 x，图形的 x 坐标默认为数组的索引
plt.show() # 显示图形