In [1]:
import numpy as np

In [2]:
a = np.random.choice(100,10)

In [5]:
np.sort(a)

array([ 2, 12, 15, 21, 27, 41, 43, 60, 72, 72])

In [8]:
a = np.array([[3,1],[4,2]])

In [10]:
np.argmax(a, axis=0)

array([1, 1], dtype=int64)

In [11]:
r = [1e2,2e3]

In [12]:
a = range(r)

TypeError: range() integer end argument expected, got list.

In [13]:
for t in r:
    print t

100.0
2000.0


In [1]:
from math import exp

In [2]:
from math import log

In [3]:
log(2)


0.6931471805599453

In [4]:
log(3)

1.0986122886681098

In [5]:
log(2.71828)

0.999999327347282

In [6]:
import numpy as np

In [10]:
a=np.array([2,3.0])

In [11]:
b = np.array([1,2])

In [12]:
a/b

array([ 2. ,  1.5])

In [13]:
a = np.array([1,2,3,4])

In [14]:
a = np.array([[1,2],[3,4]])

In [15]:
np.sum(a, axis=1)

array([3, 7])

In [16]:
a

array([[1, 2],
       [3, 4]])

In [17]:
np.sum(a,axis=1)

array([3, 7])

In [18]:
np.sum(a,axis=1,keepdims=True)

array([[3],
       [7]])

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
b = np.array([1,1,1])

In [4]:
np.dot(a,b)

6